using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ck2ModdingTool
{
    public class Modifiers
    {

        //Character attribute modifiers;
        public int diplomacy;
        public int diplomacy_penalty;
        public int stewardship;
        public int stewardship_penalty;
        public int martial;
        public int martial_penalty;
        public int intrigue;
        public int intrigue_penalty;
        public int learning;
        public int learning_penalty;
        public float fertility;
        public float fertility_penalty;
        public int health;
        public int health_penalty;
        public int combat_rating;
        public float threat_decay_speed;
        //Realm modifiers;
        public int demesne_size;
        public int vassal_limit;
        public float global_revolt_risk;
        public float local_revolt_risk;
        public float disease_defence;
        public float culture_flex;
        public float religion_flex;
        public int short_reign_length;
        public bool moved_capital_months_mult;
        //Intrigue modifiers;
        public float assassinate_chance_modifier;
        public float arrest_chance_modifier;
        public float plot_power_modifier;
        public float murder_plot_power_modifier;
        public float defensive_plot_power_modifier;
        public float plot_discovery_chance;
        //Wealth, prestige, and piety;
        public int tax_income;
        public float global_tax_modifier;
        public float local_tax_modifier;
        //public float <holding_type>_tax_modifier;
        //public float <holding_type>_vassal_tax_modifier;
        public bool nomad_tax_modifier;
        public int monthly_character_prestige;
        public bool liege_prestige;
        public float add_prestige_modifier;
        public int monthly_character_piety;
        public bool liege_piety;
        public float add_piety_modifier;
        public int monthly_character_wealth;
        //AI behavior modifiers;
        public int ai_rationality;
        public int ai_zeal;
        public int ai_greed;
        public int ai_honor;
        public int ai_ambition;
        //AI construction modifiers;
        public int ai_feudal_modifier;
        public int ai_republic_modifier;
        //Construction modifiers;
        public int build_cost_modifier;
        public int build_cost_castle_modifier;
        public int build_cost_city_modifier;
        public int build_cost_temple_modifier;
        public int build_cost_tribal_modifier;
        public int build_time_modifier;
        public int build_time_castle_modifier;
        public int build_time_city_modifier;
        public int build_time_temple_modifier;
        public int build_time_tribal_modifier;
        public float local_build_cost_modifier;
        public float local_build_cost_castle_modifier;
        public float local_build_cost_city_modifier;
        public float local_build_cost_temple_modifier;
        public float local_build_cost_tribal_modifier;
        public float local_build_time_modifier;
        public float local_build_time_castle_modifier;
        public float local_build_time_city_modifier;
        public float local_build_time_temple_modifier;
        public float local_build_time_tribal_modifier;
        //Opinion modifiers;
        public int ambition_opinion;
        public int vassal_opinion;
        public int sex_appeal_opinion;
        public int same_opinion;
        public int same_opinion_if_same_religion;
        public int opposite_opinion;
        public int liege_opinion;
        public int general_opinion;
        public int twin_opinion;
        public int dynasty_opinion;
        public int male_dynasty_opinion;
        public int female_dynasty_opinion;
        public int child_opinion;
        public int oldest_child_opinion;
        public int youngest_child_opinion;
        public int spouse_opinion;
        //public int <religion>_opinion;
        //public int <religion_group>_opinion;
        public int same_religion_opinion;
        public int infidel_opinion;
        public int christian_opinion;
        public int christian_church_opinion;
        public int church_opinion;
        public int temple_opinion;
        public int temple_all_opinion;
        public int town_opinion;
        public int city_opinion;
        public int castle_opinion;
        public int feudal_opinion;
        public int tribal_opinion;
        public int unreformed_tribal_opinion;
        public int rel_head_opinion;
        public int free_invest_vassal_opinion;
        public bool clan_sentiment;
        //Warfare modifiers;
        public float levy_size;
        //public float <holding_type>_levy_size;
        public float global_levy_size;
        public float levy_reinforce_rate;
        //public int <unit>;
        //public bool <unit>_max_levy;
        //public bool <unit>_min_levy;
        //public float <unit>_offensive;
        //public float <unit>_defensive;
        //public float <unit>_morale;
        //public float <holding_type>_vassal_min_levy;
        //public float <holding_type>_vassal_max_levy;
        public float land_morale;
        public float land_organisation;
        public bool regiment_reinforcement_speed;
        public float garrison_size;
        public float global_garrison_size;
        public bool garrison_growth;
        public int fort_level;
        public bool global_defensive;
        public bool land;
        public float global_supply_limit;
        public bool global_winter_supply;
        public float supply_limit;
        public float max_attrition;
        public float siege_defence;
        public float siege_speed;
        public float global_movement_speed;
        public float local_movement_speed;
        public float galleys_perc;
        public int retinuesize;
        public float retinuesize_perc;
        public bool retinue_maintenence_cost;
        public bool horde_maintenence_cost;
        //Technology modifiers;
        public float tech_growth_modifier;
        public int commander_limit;
        //public float tech_growth_modifier_<tech_type>;
        //public float <tech_type>_techpoints;
        //Trade modifiers;
        public int max_tradeposts;
        public int tradevalue;
        public bool trade_route_wealth;
        public bool trade_route_value;
        public bool global_trade_route_wealth;
        public bool global_trade_route_value;
        public bool global_tradevalue;
        public bool global_tradevalue_mult;
        //Population modifiers;
        public bool population_growth;
        public bool manpower_growth;
        public float max_population_mult;
        public bool max_manpower_mult;
        public int max_population;

    }
}
